title: nayfusaurus
description: Cybersecurity Engineer
baseurl: ""
url: https://nayfusaurus.github.io/

theme: cvless

# site settings
taglong: Cybersecurity Engineer
tagshort: Personal Wesite

# author settings
author:
  name: nayfusaurus
photo: assets/files/photo.png

# profile links
profile:
  tryhackme: https://tryhackme.com/r/p/nayfusaurus
  ctftime: https://ctftime.org/team/163197
  github: https://github.com/nayfusaurus
  codingame: https://www.codingame.com/profile/0ff53f8dacc172a00cb4cab0e8a884712551744
  exercism: https://exercism.org/profiles/nayfusaurus
  linkedin: https://www.linkedin.com/in/nayfusaurus/
  credly: https://www.credly.com/users/nayfusaurus
  twitter: https://x.com/nayfusaurus
  storygraph: https://app.thestorygraph.com/profile/nayfusaurus

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
